#!/usr/bin/env python3
from pathlib import Path
R=Path(__file__).resolve().parent.parent
S=R/"PROJECT_STATE.md"
V=R/"scripts/validate_phase36_postmerge_record.py"
def one(t,a,b,n):
 c=t.count(a)
 if c!=1: raise SystemExit(f"{n} expected once, found {c}")
 return t.replace(a,b,1)
s=S.read_text()
s=one(s,"**Phase 36 — Offline Consequence-Plan Review-Response Intake Envelope Validation Execution Authorization Readiness Assurance merged and validated through PR #63.**","**Phase 37 — Offline Consequence-Plan Review-Response Intake Envelope Validation Execution Authorization Decision Readiness merged and validated through PR #65.**","heading")
a="Phase 36 state: **offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-readiness-assurance-validated** (`mode: offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-readiness-assurance`, `live: false`)."
s=one(s,a,a+"\nPhase 37 state: **offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-validated** (`mode: offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness`, `live: false`).","state")
a="| 36 | Offline consequence-plan review-response intake envelope validation execution authorization readiness assurance | Merged and validated through PR #63 |"
s=one(s,a,a+"\n| 37 | Offline consequence-plan review-response intake envelope validation execution authorization decision readiness | Merged and validated through PR #65 |","row")
s=one(s,"\n## Validation\n","\n## Phase 37 result — Offline Consequence-Plan Review-Response Intake Envelope Validation Execution Authorization Decision Readiness\n\nHistorical Phase 36 finalization marker: **Phase 36 — Offline Consequence-Plan Review-Response Intake Envelope Validation Execution Authorization Readiness Assurance merged and validated through PR #63.**\n\nHistorical Phase 37 candidate marker: `exact-head validation pending`\n\nHistorical Phase 37 target marker: `offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-candidate`\n\nPhase 37 exact candidate validation passed at `b3b5cb7ce580b83b96e03dc91830c210aeb50ddd`. PR #65 was merged into `main` at commit `16516cd5b67b480a572b949996e8ebceaa8d1acb` after all 31 applicable workflows passed.\n\nAtlas remains unchanged by Principia Phase 37. Principia and Atlas retain separate lifecycle authority.\n\n```yaml\ncandidate_sha256: 724a12243300d6c91cf60fef046f5ae40089c98867bba62bdd524e3684aec2ae\ncandidate_tested_head: b3b5cb7ce580b83b96e03dc91830c210aeb50ddd\ncandidate_pull_request: 65\ncandidate_merge_commit: 16516cd5b67b480a572b949996e8ebceaa8d1acb\napplicable_candidate_workflows: 31\ndecision_policy_count: 1\ndecision_profile_count: 2\ndecision_readiness_record_count: 2\ndecision_stage_count: 24\ndecision_requirement_count: 52\ndecision_requirement_evaluated_count: 0\ndecision_option_count: 3\ndecision_option_selected_count: 0\nblank_decision_record_count: 2\nblank_decision_record_field_count: 32\nreadiness_check_count: 116\nfailed_readiness_check_count: 0\nrequired_decision_role_count: 4\ndual_control_profile_count: 2\nhuman_gate_pending_count: 8\nhuman_gate_satisfied_count: 0\nauthorization_decision_candidate_created_count: 0\nauthorization_decision_recorded_count: 0\nauthorization_granted_count: 0\nauthorization_token_issued_count: 0\nexecution_run_count: 0\nresponse_envelope_received_count: 0\nreviewer_contact_count: 0\nstatus_change_count: 0\nreal_authorization_claimed: false\ndecision: response-intake-envelope-validation-execution-authorization-decision-readiness-recorded-no-decision-candidate-created\nlive: false\n```\n\nThe recovery matrix contains 138 deterministic scenarios and rejects 137 mutations. No decision candidate, decision, grant, token, ticket, envelope, execution, reviewer contact, Atlas call, repository effect, or live activation occurred.\n\n`release/phase-37-postmerge.json` pins candidate SHA-256 `724a12243300d6c91cf60fef046f5ae40089c98867bba62bdd524e3684aec2ae`, exact tested head `b3b5cb7ce580b83b96e03dc91830c210aeb50ddd`, PR #65, merge commit `16516cd5b67b480a572b949996e8ebceaa8d1acb`, all 31 applicable workflows, frozen zero-decision authority, and final state `offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-validated`.\n\n## Validation\n","result")
a="```bash\npython3 scripts/generate_phase36_offline_consequence_plan_review_response_intake_envelope_validation_execution_authorization_readiness_assurance.py --check"
b="```bash\npython3 scripts/generate_phase37_offline_consequence_plan_review_response_intake_envelope_validation_execution_authorization_decision_readiness.py --check\npython3 scripts/validate_phase37_offline_consequence_plan_review_response_intake_envelope_validation_execution_authorization_decision_readiness.py\npython3 scripts/validate_phase37_postmerge_record.py\npython3 -m unittest software.tests.test_phase37_offline_consequence_plan_review_response_intake_envelope_validation_execution_authorization_decision_readiness -v\npython3 scripts/generate_phase36_offline_consequence_plan_review_response_intake_envelope_validation_execution_authorization_readiness_assurance.py --check"
s=one(s,a,b,"commands")
a="Next gate: **offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-candidate**.\n\nThe next bounded gate may define deterministic prerequisites for considering an authorization decision over the two assured authorization-readiness records. It must not create an authorization candidate, record a decision, grant authorization, issue or populate a token, receive an envelope, issue an execution ticket, evaluate a requirement, execute validation, record a result, select a disposition, dispatch a request, identify or contact a reviewer, satisfy a human gate, claim real authorization, start or complete review, select an outcome, activate a hold, mutate content or status, call Atlas, require external networking, or write to either repository automatically."
b="Next gate: **offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-assurance-candidate**.\n\nThe next bounded gate may independently assure the two authorization-decision readiness records, shared decision policy, profiles, inactive stages, unevaluated requirements, unselectable options, blank decision records, exact Phase 36 bindings, chained evidence, and zero-decision authority. It must not create a decision candidate, record a decision, grant authorization, issue or populate a token, receive an envelope, issue an execution ticket, evaluate a requirement, execute validation, record a result, select a disposition, dispatch a request, identify or contact a reviewer, satisfy a human gate, claim real authorization, start or complete review, select an outcome, activate a hold, mutate content or status, call Atlas, require external networking, or write to either repository automatically."
s=one(s,a,b,"next")
S.write_text(s)
v=V.read_text()
v=one(v,'CANDIDATE_SHA,HEAD,MERGE,"all 30 applicable workflows","132 deterministic scenarios","131 mutations",f"Next gate: **{NEXT}**",','CANDIDATE_SHA,HEAD,MERGE,"all 30 applicable workflows","132 deterministic scenarios","131 mutations",',"phase36 gate tuple")
a='    for marker in required:\n        if marker not in state:\n            errors.append(f"Phase 36 project-state marker missing: {marker}")\n'
b=a+'    if f"Next gate: **{NEXT}**" not in state and "Historical Phase 37 target marker: `offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-candidate`" not in state:\n        errors.append("Phase 36 next gate is neither current nor preserved historically")\n'
v=one(v,a,b,"phase36 history")
V.write_text(v)
for m in ("**Phase 37 — Offline Consequence-Plan Review-Response Intake Envelope Validation Execution Authorization Decision Readiness merged and validated through PR #65.**","Phase 37 state: **offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-validated**","Historical Phase 37 target marker: `offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-candidate`","Atlas remains unchanged by Principia Phase 37","Next gate: **offline-consequence-plan-review-response-intake-envelope-validation-execution-authorization-decision-readiness-assurance-candidate**"):
 if m not in S.read_text(): raise SystemExit("missing "+m)
print("Phase 37 state transition applied")
